services:
  # FastAPI
  - type: web
    name: fastapi-car-price-api
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MODEL_PATH
        value: app/models/model.joblib

  # Streamlit
  - type: web
    name: car-price-streamlit
    env: python
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: API_URL
        value: https://car-price-prediction-bphu.onrender.com